# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'


def common_dependency
  
  use_frameworks!
  
  pod 'Ads-Fusion-CN-Beta', '5.3.5.1', :subspecs => [
  'CSJMediation',
  'CSJMDebugTools'
  ]
  pod 'CSJMAdmobAdapter', '10.0.0.0'
  pod 'CSJMBaiduAdapter', '5.14.0'
  pod 'CSJMGdtAdapter', '4.14.30.0'
  pod 'CSJMKlevinAdapter', '2.11.0.211.1'
  pod 'CSJMKsAdapter', '3.3.42.0'
  pod 'CSJMMintegralAdapter', '7.3.4.0.1'
  pod 'CSJMSigmobAdapter', '4.8.0.0'
  pod 'CSJMUnityAdapter', '4.3.0.0'
  
  pod 'GDTMobSDK', '4.14.30'
  
end


target 'ZZGDAdSDK' do

  common_dependency

end

target 'Demo' do

  common_dependency
  
end


#, :modular_headers => true

